/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/code/editor.vue')['default']
    CoreIcon: typeof import('./src/components/core/icon/index.vue')['default']
    LayoutAppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    LayoutBasic: typeof import('./src/components/layout/Basic.vue')['default']
    Request: typeof import('./src/components/request/index.vue')['default']
    RequestCommonLayout: typeof import('./src/components/request/common/layout.vue')['default']
    RequestHttp: typeof import('./src/components/request/http/index.vue')['default']
    RequestHttpRequest: typeof import('./src/components/request/http/request.vue')['default']
    RequestHttpResponse: typeof import('./src/components/request/http/response.vue')['default']
    RequestHttpUrl: typeof import('./src/components/request/http/url.vue')['default']
  }
}
