/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/icon/index.vue')['default']
    Request: typeof import('./src/components/request/index.vue')['default']
    RequestHttp: typeof import('./src/components/request/http/index.vue')['default']
    UiButtonButton: typeof import('./src/components/ui/button/Button.vue')['default']
    UiInputGroupInputGroup: typeof import('./src/components/ui/input-group/InputGroup.vue')['default']
    UiInputGroupInputGroupAddon: typeof import('./src/components/ui/input-group/InputGroupAddon.vue')['default']
    UiInputGroupInputGroupButton: typeof import('./src/components/ui/input-group/InputGroupButton.vue')['default']
    UiInputGroupInputGroupInput: typeof import('./src/components/ui/input-group/InputGroupInput.vue')['default']
    UiInputGroupInputGroupText: typeof import('./src/components/ui/input-group/InputGroupText.vue')['default']
    UiInputGroupInputGroupTextarea: typeof import('./src/components/ui/input-group/InputGroupTextarea.vue')['default']
    UiInputInput: typeof import('./src/components/ui/input/Input.vue')['default']
    UiSelectSelect: typeof import('./src/components/ui/select/Select.vue')['default']
    UiSelectSelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    UiSelectSelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    UiSelectSelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    UiSelectSelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    UiSelectSelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    UiSelectSelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    UiSelectSelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    UiSelectSelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    UiSelectSelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    UiSelectSelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    UiSeparatorSeparator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    UiSheetSheet: typeof import('./src/components/ui/sheet/Sheet.vue')['default']
    UiSheetSheetClose: typeof import('./src/components/ui/sheet/SheetClose.vue')['default']
    UiSheetSheetContent: typeof import('./src/components/ui/sheet/SheetContent.vue')['default']
    UiSheetSheetDescription: typeof import('./src/components/ui/sheet/SheetDescription.vue')['default']
    UiSheetSheetFooter: typeof import('./src/components/ui/sheet/SheetFooter.vue')['default']
    UiSheetSheetHeader: typeof import('./src/components/ui/sheet/SheetHeader.vue')['default']
    UiSheetSheetOverlay: typeof import('./src/components/ui/sheet/SheetOverlay.vue')['default']
    UiSheetSheetTitle: typeof import('./src/components/ui/sheet/SheetTitle.vue')['default']
    UiSheetSheetTrigger: typeof import('./src/components/ui/sheet/SheetTrigger.vue')['default']
    UiSidebarSidebar: typeof import('./src/components/ui/sidebar/Sidebar.vue')['default']
    UiSidebarSidebarContent: typeof import('./src/components/ui/sidebar/SidebarContent.vue')['default']
    UiSidebarSidebarFooter: typeof import('./src/components/ui/sidebar/SidebarFooter.vue')['default']
    UiSidebarSidebarGroup: typeof import('./src/components/ui/sidebar/SidebarGroup.vue')['default']
    UiSidebarSidebarGroupAction: typeof import('./src/components/ui/sidebar/SidebarGroupAction.vue')['default']
    UiSidebarSidebarGroupContent: typeof import('./src/components/ui/sidebar/SidebarGroupContent.vue')['default']
    UiSidebarSidebarGroupLabel: typeof import('./src/components/ui/sidebar/SidebarGroupLabel.vue')['default']
    UiSidebarSidebarHeader: typeof import('./src/components/ui/sidebar/SidebarHeader.vue')['default']
    UiSidebarSidebarInput: typeof import('./src/components/ui/sidebar/SidebarInput.vue')['default']
    UiSidebarSidebarInset: typeof import('./src/components/ui/sidebar/SidebarInset.vue')['default']
    UiSidebarSidebarMenu: typeof import('./src/components/ui/sidebar/SidebarMenu.vue')['default']
    UiSidebarSidebarMenuAction: typeof import('./src/components/ui/sidebar/SidebarMenuAction.vue')['default']
    UiSidebarSidebarMenuBadge: typeof import('./src/components/ui/sidebar/SidebarMenuBadge.vue')['default']
    UiSidebarSidebarMenuButton: typeof import('./src/components/ui/sidebar/SidebarMenuButton.vue')['default']
    UiSidebarSidebarMenuButtonChild: typeof import('./src/components/ui/sidebar/SidebarMenuButtonChild.vue')['default']
    UiSidebarSidebarMenuItem: typeof import('./src/components/ui/sidebar/SidebarMenuItem.vue')['default']
    UiSidebarSidebarMenuSkeleton: typeof import('./src/components/ui/sidebar/SidebarMenuSkeleton.vue')['default']
    UiSidebarSidebarMenuSub: typeof import('./src/components/ui/sidebar/SidebarMenuSub.vue')['default']
    UiSidebarSidebarMenuSubButton: typeof import('./src/components/ui/sidebar/SidebarMenuSubButton.vue')['default']
    UiSidebarSidebarMenuSubItem: typeof import('./src/components/ui/sidebar/SidebarMenuSubItem.vue')['default']
    UiSidebarSidebarProvider: typeof import('./src/components/ui/sidebar/SidebarProvider.vue')['default']
    UiSidebarSidebarRail: typeof import('./src/components/ui/sidebar/SidebarRail.vue')['default']
    UiSidebarSidebarSeparator: typeof import('./src/components/ui/sidebar/SidebarSeparator.vue')['default']
    UiSidebarSidebarTrigger: typeof import('./src/components/ui/sidebar/SidebarTrigger.vue')['default']
    UiSkeletonSkeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    UiTextareaTextarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
    UiTooltipTooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    UiTooltipTooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    UiTooltipTooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    UiTooltipTooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
