// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apexa/service"
	"context"
	"github.com/wailsapp/wails/v3/pkg/application"
)

import (
	_ "embed"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(contextContext context.Context) (*application.App, error) {
	collectionsService := service.NewCollectionsService()
	app := newApp(collectionsService)
	return app, nil
}
